# Generated by Django 5.2 on 2025-05-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(max_length=4)),
                ('img2', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
